### ISSUE TITLE
Separate setting/config information from Code

### ISSUE THREAD

**Issue by alucardthefish** [BrianRuizy/bookomate#13]
**Is your feature request related to a problem? Please describe.**

For security reasons, It is a good practice to separate the code from settings files and avoid exposing sensitive database information like passwords and Django secret key or any external services credentials.

**Describe the solution you'd like**

It would be great to implement a system which allows to read from an ignored file all the personal settings like debug mode, db info, secret_key an so, and set them in the settings.py file.

**Describe alternatives you've considered**

An alternative could be to use a library such as decouple. 

**Additional context**

**Comment by jeremychrimes** [comment]
If we were to go down this path it would be highly advisable to create a setup file for new contributors to help them to setup the required parameters. 
I have read the documentation for [python-decouple](https://pypi.org/project/python-decouple/) as suggested in the issue from @alucardthefish and it seems like the library would be a good fit for the project pending approval from @mateuszz0000 & @BrianRuizy. @alucardthefish If you could please draft a pull request of the implementation of the decouple implementation I would be happy to write a setup file. 

Cheers 👍

**Comment by l3str4nge** [comment]
Agreed in 100%. I think we can create `.env` file with all necessary things. It will also helps with future dockerizing :smiley:

**Comment by alucardthefish** [comment]
> If we were to go down this path it would be highly advisable to create a setup file for new contributors to help them to setup the required parameters.
> I have read the documentation for [python-decouple](https://pypi.org/project/python-decouple/) as suggested in the issue from @alucardthefish and it seems like the library would be a good fit for the project pending approval from @mateuszz0000 & @BrianRuizy. @alucardthefish If you could please draft a pull request of the implementation of the decouple implementation I would be happy to write a setup file.
> 
> Cheers +1

Sure, I'm working on it right now.
