### ISSUE TITLE
Requirements.txt - psycopg2

### ISSUE THREAD

**Issue by jeremychrimes** [BrianRuizy/bookomate#15]
**Describe the bug**
When installing packages via pip an error is thrown regarding the package psycopg2 requiring pg_config. 

What is the functionality of psycopg2 and is it 100% necessary or could we go without? Otherwise what could we do to document it as a requirement to setup the development environment in order to help new contributors?  

**To Reproduce**
1. Clone the repository `% git clone git@github.com:Bookomate/bookomate.git`
2. Change directory to bookomate `% cd bookomate`
3. Create a Python Virtual Environment and activate `% python -m venv env` `% source env/bin/activate`.
4. Install the requirements via pip `pip install -r requirements.txt`

**Expected behavior**
The expected behaviour is that it would install all requirements without throwing an error. 

**Screenshots**
`
 ERROR: Command errored out with exit status 1:
     command: /Users/jeremychrimes/repos/bookomate/env/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/mb/q3232p712dqbpfz17rlyqq2r0000gn/T/pip-install-ggdaihfq/psycopg2/setup.py'"'"'; __file__='"'"'/private/var/folders/mb/q3232p712dqbpfz17rlyqq2r0000gn/T/pip-install-ggdaihfq/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /private/var/folders/mb/q3232p712dqbpfz17rlyqq2r0000gn/T/pip-install-ggdaihfq/psycopg2/
    Complete output (23 lines):
    running egg_info
    creating pip-egg-info/psycopg2.egg-info
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
    
    Error: pg_config executable not found.
    
    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:
    
        python setup.py build_ext --pg-config /path/to/pg_config build ...
    
    or with the pg_config option in 'setup.cfg'.
    
    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.
    
    For further information please check the 'doc/src/install.rst' file (also at
    <https://www.psycopg.org/docs/install.html>).
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`

**Desktop:**
 - OS: MacOS Catalina 10.15.5
 - Stack: Python 3.7.6 installed from homebrew, pip 19.2.3 ZSH

**Comment by l3str4nge** [comment]
`psychopg` is lib for postgresql usage in django. 

I made a little investigation. Could you try following step? 
`pip install psycopg2-binary`
I cannot because i don't have macos.

**Comment by jeremychrimes** [comment]
Thanks @mateuszz0000, Ok the pip package `psycopg2-binary`  will install the psycopg2 library on mac. Although even installed pip will still throw an error. Although if you remove the psycopg2 library from the requirements.txt will run without throwing an error. Does changing it to the `psycopg2-binary` version break anything on windows?

**Comment by l3str4nge** [comment]
@jeremychrimes do you have installed postgresql on your machine? `psychopg` installation fails because you probably dont have it. Please uninstall either `psycopg` and `psycopg2-binary` and try:
`brew install postgresql`. If works we need to update README.md for postgresql installation.

**Comment by alucardthefish** [comment]
Yes, it is necessary to have installed postgres in your machine. In my case, I had to install libpq-dev to successfully install. 

link which helps me to fix it:

https://www.techiediaries.com/error-you-need-to-install-postgresql-server-dev-x-y-for-building-a-server-side-extension-or-libpq-dev-for-building-a-client-side-application/

**Comment by l3str4nge** [comment]
Its need to update readme installation section with note  about postgresql dependency.

**Comment by jeremychrimes** [comment]
Ok, @mateuszz0000 Installing Postgresql resolves the issue I will write a PR to add that postgresql is a requirement for the development setup.
