### ISSUE TITLE
Add Travis CI integration

### ISSUE THREAD

**Issue by l3str4nge** [BrianRuizy/bookomate#2]

**Comment by alucardthefish** [comment]
It requires the owner to do it. Here is the tuto.

https://docs.travis-ci.com/user/tutorial/

**Comment by BrianRuizy** [comment]
I integrated [Travis ](https://travis-ci.com/github/Bookomate/bookomate)into our project, now we just need to add some _tests_ to **travis.yml** and it's a done deal!

**Comment by BrianRuizy** [comment]
Closing now due to successful Travis integration and passing [build](https://travis-ci.com/github/Bookomate/bookomate/builds/170881423) ✔.
