### ISSUE TITLE
Project structure

### ISSUE THREAD

**Issue by l3str4nge** [BrianRuizy/bookomate#20]
I opened this issue for project structure discussion. My proposition is something like in this project:
https://github.com/mirumee/saleor
```
bookomate/
    - bookomate
        - app1/
        - app2/
        - app3/
        - settings/
        - wsgi.py
        - urls.py
    - manage.py
    - .gitignore.txt
    -  readme.md
    -  .travis.yml
```

@BrianRuizy @jeremychrimes what do you think?

**Comment by BrianRuizy** [comment]
Okay, good that you mention. Is there any difference between that structure and having different apps at the root directory?

**Comment by l3str4nge** [comment]
The only difference is that you have all aps in one place without unnecessary files like travis config or setup.py. Navigation in project is easier.

**Comment by BrianRuizy** [comment]
Got it. Just wondering because I've seen various approaches. 
And, how about _**templates/**_, should it be at root or in **_bookomate/bookomate_**?

**Comment by jeremychrimes** [comment]
I am happy with the structure I feel that it is quite simple for new developers & contributors. I think that templates should be in the bookomate/bookomate directory.

**Comment by l3str4nge** [comment]
So current structure is approved by everyone, right? :smiley:
