### ISSUE TITLE
update forms to follow present UI

### ISSUE THREAD

**Issue by BrianRuizy** [BrianRuizy/bookomate#29]
Update the following form pages, to follows the present UI found on the login-form page:

- Sign-up page
- Logout page
- Logout confirmation
- Password reset page
- Password reset confirmation

**Comment by ivuckovic** [comment]
Hey,
I'd like to take this task.

**Comment by BrianRuizy** [comment]
@ivuckovic, go for it! We welcome all contributions. 
Feel free to comment back, or reach out trough [Gitter](https://gitter.im/Bookomate/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link) if you have any questions.
