### ISSUE TITLE
Frontend bootstrap templates

### ISSUE THREAD

**Issue by l3str4nge** [BrianRuizy/bookomate#3]
Let's discuss about frontend tools. I prefer bootstrap 4 because it's easy to use and look pretty good.

**Comment by BrianRuizy** [comment]
I second that, BS4 is great, and easy to learn for others.

**Comment by pianokidd03** [comment]
Awesome, I'm cool with bootstrap too.

**Comment by l3str4nge** [comment]
So go ahead with bootstrap. @pianokidd03 do you want prepare templates?

**Comment by pianokidd03** [comment]
Sure, I am currently making the base html file that rest of the pages will inherit from. 

Currently, I'm envisioning this base template to have a nav bar with an account settings page and calendar page listed (of course neither of these pages have been created yet, so they'll just be empty links 😂). 

There will also be a footer with a link to contribute and some other info.

**Comment by BrianRuizy** [comment]
![mockup_bookomate](https://user-images.githubusercontent.com/23439187/84585788-df5a4e00-add8-11ea-8abc-4035f825a14e.png)
