### ISSUE TITLE
Add login via social media

### ISSUE THREAD

**Issue by l3str4nge** [BrianRuizy/bookomate#4]
Project need functionality which provides signin/signup pages.

 Allauth lib for django is great for that:
https://django-allauth.readthedocs.io/en/latest/installation.html

**Comment by alucardthefish** [comment]
Which database will be used in this project?

**Comment by l3str4nge** [comment]
I think PostgreSQL will be best.

**Comment by l3str4nge** [comment]
@BrianRuizy I thought about https://django-allauth.readthedocs.io/en/latest/installation.html with this integration with don't need create separated views for signup etc just customize frontend. Also we have integration with social media out of the box.

**Comment by BrianRuizy** [comment]
_allauth_l, got it!

**Comment by BrianRuizy** [comment]
_allauth_, got it!
